server:
  host: "http://127.0.0.1"
  port: 4723
  path: "/wd/hub"
  full_server_path: "http://127.0.0.1:4723/wd/hub"

capabilities:
  platformName: "Android"
  deviceName: "emulator-5554"
  appPackage: "com.example.myapp"
  appActivity: ".MainActivity"
  automationName: "UiAutomator2"

applications:
  calculator:
    appPackage: "com.google.android.calculator"
    appActivity: "com.android.calculator2.Calculator"
    noReset: False
camera:
  appPackage: "com.sec.android.app.camera"
  appActivity: ".Camera"
messages:
contacts:
clock:
  appPackage: "com.sec.android.app.clockpackage"
  appActivity: ".ClockPackage"
  noReset: False
  fullReset: False
  dontStopAppOnReset: True